/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Purchase {
  'id' : bigint,
  'accessKey' : [] | [string],
  'scriptId' : bigint,
  'purchasedAt' : Time,
  'buyerPrincipal' : Principal,
}
export interface Script {
  'id' : bigint,
  'accessKey' : [] | [string],
  'title' : string,
  'changelog' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'language' : string,
  'version' : string,
  'imageKey' : string,
  'category' : string,
  'price' : bigint,
  'requirements' : string,
  'fileKey' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'email' : string,
  'userPrincipal' : Principal,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreateScript' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    string
  >,
  'adminDeleteScript' : ActorMethod<[bigint], string>,
  'adminGetAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'adminGetStats' : ActorMethod<[], string>,
  'adminUpdateScript' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyPurchases' : ActorMethod<[], Array<Purchase>>,
  'getScriptById' : ActorMethod<[bigint], [] | [Script]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToAdmin' : ActorMethod<[Principal], string>,
  'purchaseScript' : ActorMethod<[bigint], string>,
  'registerUser' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleUserStatus' : ActorMethod<[Principal], string>,
  'suspendUser' : ActorMethod<[Principal], string>,
  'demoteFromAdmin' : ActorMethod<[Principal], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];