/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'accessKey' : IDL.Opt(IDL.Text),
  'scriptId' : IDL.Nat,
  'purchasedAt' : Time,
  'buyerPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'isAdmin' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Script = IDL.Record({
  'id' : IDL.Nat,
  'accessKey' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'changelog' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'language' : IDL.Text,
  'version' : IDL.Text,
  'imageKey' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'requirements' : IDL.Text,
  'fileKey' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminCreateScript' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'adminDeleteScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'adminGetAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'adminGetStats' : IDL.Func([], [IDL.Text], ['query']),
  'adminUpdateScript' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getScriptById' : IDL.Func([IDL.Nat], [IDL.Opt(Script)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'purchaseScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleUserStatus' : IDL.Func([IDL.Principal], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'accessKey' : IDL.Opt(IDL.Text),
    'scriptId' : IDL.Nat,
    'purchasedAt' : Time,
    'buyerPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'isAdmin' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Script = IDL.Record({
    'id' : IDL.Nat,
    'accessKey' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'changelog' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'language' : IDL.Text,
    'version' : IDL.Text,
    'imageKey' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'requirements' : IDL.Text,
    'fileKey' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminCreateScript' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'adminDeleteScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'adminGetAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'adminGetStats' : IDL.Func([], [IDL.Text], ['query']),
    'adminUpdateScript' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getScriptById' : IDL.Func([IDL.Nat], [IDL.Opt(Script)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'purchaseScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleUserStatus' : IDL.Func([IDL.Principal], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };